# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# НАСТРОЙКА КЭША: Перенаправляем файлы в чистую папку без русских букв
gradle.user.home=C:/gradle

## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.20.1,1.21)
# The Forge version must agree with the Minecraft version to get a valid artifact
forge_version=47.4.10
# The Forge version range can use any version of Forge as bounds or match the loader version range
forge_version_range=[47,)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[47,)
# The mapping channel to use for mappings.
mapping_channel=official
# The mapping version to query from the mapping channel.
mapping_version=1.20.1


## Mod Properties

# Изменили ID мода под наш проект
mod_id=multiplayer
mod_name=MCMultiplayer
mod_license=MIT
mod_version=5.4.0
mod_group_id=com.multiplayer
mod_authors=Denis VirusNew
mod_description=A mod for seamless multiplayer play with friends. It automatically detects and displays your local and global IP addresses, allows quick clipboard copying via hotkeys, and features a one-click WAN server creation directly from the ESC pause menu using native UPnP port mapping. Additionally includes built-in advanced server host tools for banning and pardoning players by username and IP address.
org.gradle.java.home=C:/Program Files/Java/jdk-17